In [1]:
import numpy as np
from scipy import spatial

Create word embedding vectors and save them into a dict using the pre-trained embeddings.

In [3]:
embeddings_dict = {}

with open("dolma_300_2024_1.2M.100_combined.txt", 'r', encoding="utf-8") as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[word] = vector

Define a method to find nearest words using spatial from Scipy.

In [4]:
def find_closest_embeddings(embedding):
    return sorted(embeddings_dict.keys(), key=lambda word: spatial.distance.euclidean(embeddings_dict[word], embedding))

Printing out the embeddings vector for the words 'queen', 'king' and 'man'.

In [6]:
embeddings_dict["queen"]

array([ 1.346120e-01, -1.573400e-01, -2.564860e-01,  6.176650e-01,
       -4.015000e-02,  2.531290e-01, -1.245940e-01, -4.359800e-02,
        1.257054e+00,  2.835240e-01,  1.953220e-01, -3.198940e-01,
       -6.397000e-03, -1.067090e-01, -3.555500e-02, -2.728750e-01,
        2.658540e-01, -8.437100e-02, -2.300130e-01,  5.121600e-02,
       -2.594800e-02,  1.465000e-01, -6.495850e-01, -7.637950e-01,
       -4.174720e-01, -1.931310e-01, -1.641000e-03, -6.747300e-02,
        3.026200e-02, -2.057000e-03,  4.854400e-01,  1.748600e-02,
        3.420730e-01,  4.989900e-02,  4.460120e-01, -3.425860e-01,
        1.209120e-01,  1.495750e-01, -2.425900e-01,  1.682870e-01,
       -4.918740e-01,  1.788190e-01,  1.181170e-01, -4.143580e-01,
        1.698460e-01, -1.952500e-02,  2.205040e-01, -3.528890e-01,
       -2.838380e-01,  1.917700e-02,  2.199000e-02, -1.491740e-01,
        2.015790e-01,  8.640000e-04, -3.395330e-01,  6.372600e-02,
        9.930500e-02, -1.542820e-01, -2.349010e-01, -4.844400e

In [7]:
embeddings_dict["king"]

array([ 6.603200e-02, -2.294820e-01, -3.092080e-01,  4.549960e-01,
       -1.933340e-01,  2.746510e-01,  1.203650e-01, -1.889070e-01,
        1.100442e+00, -4.446100e-02, -1.360030e-01, -3.324510e-01,
        1.657720e-01,  1.898240e-01,  1.087910e-01, -2.284600e-01,
        7.749300e-02, -1.664380e-01, -3.570940e-01,  1.221390e-01,
        2.770400e-01, -2.228850e-01, -7.497440e-01, -4.372610e-01,
       -3.963830e-01, -4.035970e-01,  2.090570e-01,  8.307100e-02,
       -4.926000e-03, -4.306340e-01,  8.482200e-02, -1.756540e-01,
       -2.968540e-01,  9.071300e-02,  2.550830e-01,  1.958340e-01,
       -1.431590e-01,  5.924200e-02, -1.708500e-02,  1.498600e-02,
       -5.592000e-03, -7.950700e-02, -4.498140e-01, -3.083240e-01,
        5.127140e-01, -5.942900e-02,  1.379540e-01, -3.557770e-01,
        9.933300e-02, -6.155600e-02, -2.693070e-01,  2.911750e-01,
        3.337060e-01, -4.296770e-01, -9.582300e-02,  1.487830e-01,
        3.276330e-01,  7.061000e-03,  8.776200e-02,  1.902720e

In [8]:
embeddings_dict["man"]

array([ 1.375030e-01, -1.436380e-01, -3.298050e-01, -1.559280e-01,
        5.238300e-02,  4.836300e-02, -2.421760e-01,  1.636030e-01,
        1.132815e+00,  2.229040e-01, -3.317540e-01, -4.418450e-01,
       -1.832710e-01, -4.622600e-01,  4.048160e-01, -5.591500e-02,
       -1.951210e-01, -7.066400e-02, -6.918500e-02, -9.375100e-02,
       -4.324830e-01, -5.431820e-01, -5.811880e-01,  5.155300e-02,
       -3.259510e-01, -1.871500e-01,  2.676290e-01,  2.822390e-01,
       -5.132100e-02, -6.310340e-01,  1.172140e-01, -3.045000e-03,
       -2.613280e-01,  1.483060e-01,  4.462840e-01,  1.843920e-01,
       -1.378340e-01,  2.670250e-01,  1.696410e-01, -3.139150e-01,
        2.384060e-01, -2.437330e-01, -5.507280e-01, -3.646250e-01,
        3.417750e-01,  2.272110e-01,  5.296040e-01,  2.520700e-02,
        3.831680e-01,  2.509900e-02, -1.829260e-01,  2.238910e-01,
        1.522670e-01, -1.365490e-01,  1.016490e-01,  9.450200e-02,
        3.425370e-01,  1.364990e-01,  3.930000e-03,  4.177120e

4 closest words to 'king' in the embedding space.

In [5]:
find_closest_embeddings(embeddings_dict["king"])[:5]

['king', 'prince', 'queen', 'kings', 'throne']

Trying vec("woman") - vec("man) + vec("king") and finding the closest word:

In [10]:
print(find_closest_embeddings(
    embeddings_dict["woman"] - embeddings_dict["man"] + embeddings_dict["king"]
)[:1])

['queen']
